# Generated by Django 4.2.3 on 2023-07-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('data_de_registro', models.DateField()),
                ('depoimento_descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
