# Generated by Django 4.2.3 on 2023-07-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_rename_nomecompleto_depoimento_nome_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
